# deploy-app.yml

---
- name: Upload App and Confgure PHP
  hosts: webserver
  become: true
  tasks:
  - name: Upload application file
    copy:
      src: app/index.php
      dest: /var/www/html
      mode: 0755

  - name: Configure php.ini file
    lineinfile:
      path: /etc/php.ini
      regexp: ^short_open_tag
      line: 'short_open_tag=On'

  - name: restart apache
    service: name=httpd state=restarted